#配置服务器信息
server:
  port: 8001
  #context-path: /study 配置根目录


##数据库信息配置
spring:
  application:
    name: micservice-dept-service  #应用名称
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: C##song
    password: toor
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


