#配置服务器信息
server:
  port: 8001
  #context-path: /study 配置根目录


##数据库信息配置
spring:
  application:
    name: micservice-dept-service  #应用名称
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa123456
    url: jdbc:mysql://120.27.240.124:3306/springcloud

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


